services:
    jupyter:
        name: Jupyter Notebook
        description: Jupyter Notebook
        triggeredBy:
            - manual
        commands:
            start: "jupyter lab --port 8888 --ServerApp.token='' --ServerApp.allow_remote_access=true --no-browser"